pipeline {
    agent any

    tools {
        maven 'Maven 3.9.2' // Adjust this to your Maven version
        jdk 'JDK 11' // Adjust this to your JDK version
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}


